### ISSUE TITLE
Cannot install geopandas in fresh environment.

### ISSUE THREAD

**Issue by TimoRoth** [conda-forge/geopandas-feedstock#53] opened 2019-03-21 13:05 UTC
```
$ conda create -n test_env -c conda-forge python==3.7 geopandas
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - geopandas
Use "conda search <package> --info" to see the dependencies for each package.
```

This is directly related to channel_priority=strict being set, without that, it manages to install, but ends up like described in issue #48 where libpoppler.so.76 is missing.

In another, already pre-existing environment, it gives out a bit more descriptive of an error:
```
$ conda install -c conda-forge -c defaults geopandas
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - rtree==0.8.3=py36_1000 -> libspatialindex==1.8

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by jorisvandenbossche** [comment] 2019-03-21 13:08
I can confirm this, cc @ocefpaf

**Comment by jorisvandenbossche** [comment] 2019-03-21 13:13
Seems there is indeed a problem with rtree. Only trying to install fiona and rtree gives:

```
joris@joris-XPS-13-9350:~/scipy$ conda create -n test_env -c conda-forge python=3.7 fiona rtree
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - rtree
Use "conda search <package> --info" to see the dependencies for each package.
```

although that if I try to install fiona and libspatialindex (the only dependency of rtree), then it works fine ..

**Comment by jorisvandenbossche** [comment] 2019-03-21 13:18
@ocefpaf I see you changed the pinning of libspatialindex recently to 1.9: https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/4b273715fe2c25a60288ceb54318ea61082ba90d#diff-8926f6e7808be490ec92ac38016ab868. 
But, if you just ask to install it, conda-forge gives you 1.8, and I also don't see any version 1.9 for libspatialindex.

**Comment by ocefpaf** [comment] 2019-03-21 13:33
It is probably related to the repo patch I applied earlier this week :unamused: 

Looking into it...

**Comment by ocefpaf** [comment] 2019-03-21 13:40
@soapy1 do you know what may be going on here? Should we revert https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/14?

**Comment by gboeing** [comment] 2019-03-21 15:07
> I can confirm this on linux, cc @ocefpaf

Can confirm this on Windows too.

**Comment by soapy1** [comment] 2019-03-21 15:35
so for some reason, I can't reproduce this issue and I get the 1.9 libspatialindex. If someone can test with setting `channel_alias: https://conda-web.anaconda.org` in their .condarc. This will make conda get the unpatched repodata. So if that resolves the issue then conda-forge/conda-forge-repodata-patches-feedstock#14 should be reverted. Looking into this a bit more

**Comment by ocefpaf** [comment] 2019-03-21 16:36
> so for some reason, I can't reproduce this issue and I get the 1.9 libspatialindex. 

I just merged `libspatialindex 1.9` but the old `rtree` should be installable with `libspatialindex 1.8` before I merged it :-/

>  Looking into this a bit more

Thanks!

**Comment by soapy1** [comment] 2019-03-21 17:33
Sooooo, it looks like the repodata hotfix is the culprit here. I think the pinning can be readjusted @ocefpaf

**Comment by ocefpaf** [comment] 2019-03-21 17:35
> Sooooo, it looks like the repodata hotfix is the culprit here. I think the pinning can be readjusted @ocefpaf

I'll revert that PR but not sure how to fix the repo hotfix.

**Comment by ocefpaf** [comment] 2019-03-21 18:05
@TimoRoth and @gboeing can you please test that again? I did not really "fix it" I only removed the "bad fix" and push new packages. Hopefully things should work with `libspatialindex 1.9.0` on  Linux and macOS and `libspatialindex 1.8.5` on Windows.

I'll try to push `libspatialindex 1.9` on Windows over the weekend.

**Comment by soapy1** [comment] 2019-03-21 18:07
so, I think if the pin is changed to `<1.9` or `1.8.*` it should be resolved. It seems like conda is trying to match exactly to 1.8 and that doesn't really work.

**Comment by ocefpaf** [comment] 2019-03-21 18:10
> so, I think if the pin is changed to `<1.9` or `1.8.*` it should be resolved. It seems like conda is trying to match exactly to 1.8 and that doesn't really work.

Got it. Thanks! However, `libspatialindex` has only 2 children (`rtree` and `qgis`) so I'm fixing this one "by hand" now and leave repo data patch for the next time this happens.

**Comment by jorisvandenbossche** [comment] 2019-03-21 18:41
A basic `conda create -n test_env -c conda-forge python=3.7 geopandas` now works again!

**Comment by ocefpaf** [comment] 2019-03-21 18:45
> A basic `conda create -n test_env -c conda-forge python=3.7 geopandas` now works again!

Thanks for checking (and sorry for yet another broken env).
We'll learn how to do this eventually ;-p

**Closed by ocefpaf** 2019-03-21 18:45 UTC

**Comment by gboeing** [comment] 2019-03-21 18:50
Looks like it's working again on Windows. Thanks!
